[build]
  publish = "frontend"

[[redirects]]
  from = "/backend/*"
  to = "https://your-backend-url.herokuapp.com/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200